require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ConseillesController, type: :controller do
  
  before(:each) do
    @user = User.create!(
      :nom => "foo",
      :prenom => "Prenom",
      :sexe => "Sexe",
      :adresse => "Adresse",
      :password_digest => "Password Digest"      
    )
    end
  # This should return the minimal set of attributes required to create a valid
  # Conseille. As you add validations to Conseille, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {nom: "toto", prenom: "tata"}
  }

  let(:invalid_attributes) {
    {nom: "", prenom: "tata"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConseillesController. Be sure to keep this updated too.
  let(:valid_session) { {user_id:User.first.id} }

  describe "GET #index" do
    it "assigns all conseilles as @conseilles" do
      conseille = Conseille.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:conseilles)).to eq([conseille])
    end
  end

  describe "GET #show" do
    it "assigns the requested conseille as @conseille" do
      conseille = Conseille.create! valid_attributes
      get :show, {:id => conseille.to_param}, valid_session
      expect(assigns(:conseille)).to eq(conseille)
    end
  end

  describe "GET #new" do
    it "assigns a new conseille as @conseille" do
      get :new, {}, valid_session
      expect(assigns(:conseille)).to be_a_new(Conseille)
    end
  end

  describe "GET #edit" do
    it "assigns the requested conseille as @conseille" do
      conseille = Conseille.create! valid_attributes
      get :edit, {:id => conseille.to_param}, valid_session
      expect(assigns(:conseille)).to eq(conseille)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Conseille" do
        expect {
          post :create, {:conseille => valid_attributes}, valid_session
        }.to change(Conseille, :count).by(1)
      end

      it "assigns a newly created conseille as @conseille" do
        post :create, {:conseille => valid_attributes}, valid_session
        expect(assigns(:conseille)).to be_a(Conseille)
        expect(assigns(:conseille)).to be_persisted
      end

      it "redirects to the created conseille" do
        post :create, {:conseille => valid_attributes}, valid_session
        expect(response).to redirect_to(Conseille.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved conseille as @conseille" do
        post :create, {:conseille => invalid_attributes}, valid_session
        expect(assigns(:conseille)).to be_a_new(Conseille)
      end

      it "re-renders the 'new' template" do
        post :create, {:conseille => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {nom: "toto", prenom: "tata"}
      }

      it "updates the requested conseille" do
        conseille = Conseille.create! valid_attributes
        put :update, {:id => conseille.to_param, :conseille => new_attributes}, valid_session
        conseille.reload

      end

      it "assigns the requested conseille as @conseille" do
        conseille = Conseille.create! valid_attributes
        put :update, {:id => conseille.to_param, :conseille => valid_attributes}, valid_session
        expect(assigns(:conseille)).to eq(conseille)
      end

      it "redirects to the conseille" do
        conseille = Conseille.create! valid_attributes
        put :update, {:id => conseille.to_param, :conseille => valid_attributes}, valid_session
        expect(response).to redirect_to(conseille)
      end
    end

    context "with invalid params" do
      it "assigns the conseille as @conseille" do
        conseille = Conseille.create! valid_attributes
        put :update, {:id => conseille.to_param, :conseille => invalid_attributes}, valid_session
        expect(assigns(:conseille)).to eq(conseille)
      end

      it "re-renders the 'edit' template" do
        conseille = Conseille.create! valid_attributes
        put :update, {:id => conseille.to_param, :conseille => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested conseille" do
      conseille = Conseille.create! valid_attributes
      expect {
        delete :destroy, {:id => conseille.to_param}, valid_session
      }.to change(Conseille, :count).by(-1)
    end

    it "redirects to the conseilles list" do
      conseille = Conseille.create! valid_attributes
      delete :destroy, {:id => conseille.to_param}, valid_session
      expect(response).to redirect_to(conseilles_url)
    end
  end

end
