require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LitigesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Litige. As you add validations to Litige, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {identifiant:"ER123", status:"Nouveau", motif:"blah"}
  }

  let(:invalid_attributes) {
    {identifiant:"E123", status:"Nouveau", motif:"blah"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LitigesController. Be sure to keep this updated too.
  let(:valid_session) { {user_id:User.first.id} }

  describe "GET #index" do
    it "assigns all litiges as @litiges" do
      litige = Litige.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:litiges)).to eq([litige])
    end
  end

  describe "GET #show" do
    it "assigns the requested litige as @litige" do
      litige = Litige.create! valid_attributes
      get :show, {:id => litige.to_param}, valid_session
      expect(assigns(:litige)).to eq(litige)
    end
  end

  describe "GET #new" do
    it "assigns a new litige as @litige" do
      get :new, {}, valid_session
      expect(assigns(:litige)).to be_a_new(Litige)
    end
  end

  describe "GET #edit" do
    it "assigns the requested litige as @litige" do
      litige = Litige.create! valid_attributes
      get :edit, {:id => litige.to_param}, valid_session
      expect(assigns(:litige)).to eq(litige)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Litige" do
        expect {
          post :create, {:litige => valid_attributes}, valid_session
        }.to change(Litige, :count).by(1)
      end

      it "assigns a newly created litige as @litige" do
        post :create, {:litige => valid_attributes}, valid_session
        expect(assigns(:litige)).to be_a(Litige)
        expect(assigns(:litige)).to be_persisted
      end

      it "redirects to the created litige" do
        post :create, {:litige => valid_attributes}, valid_session
        expect(response).to redirect_to(Litige.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved litige as @litige" do
        post :create, {:litige => invalid_attributes}, valid_session
        expect(assigns(:litige)).to be_a_new(Litige)
      end

      it "re-renders the 'new' template" do
        post :create, {:litige => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {identifiant:"ER123", status:"Nouveau", motif:"blahblah"}
      }

      it "updates the requested litige" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => new_attributes}, valid_session
        litige.reload

      end

      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => valid_attributes}, valid_session
        expect(assigns(:litige)).to eq(litige)
      end

      it "redirects to the litige" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => valid_attributes}, valid_session
        expect(response).to redirect_to(litige)
      end
    end

    context "with invalid params" do
      it "assigns the litige as @litige" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => invalid_attributes}, valid_session
        expect(assigns(:litige)).to eq(litige)
      end

      it "re-renders the 'edit' template" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested litige" do
      litige = Litige.create! valid_attributes
      expect {
        delete :destroy, {:id => litige.to_param}, valid_session
      }.to change(Litige, :count).by(-1)
    end

    it "redirects to the litiges list" do
      litige = Litige.create! valid_attributes
      delete :destroy, {:id => litige.to_param}, valid_session
      expect(response).to redirect_to(litiges_url)
    end
  end

end
