require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
require 'helpers/setup'
RSpec.describe LitigesController, type: :controller do
  
  # This should return the minimal set of attributes required to create a valid
  # Litige. As you add validations to Litige, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {identifiant:"ER129", status:"Nouveau", motif:"blah", transaction_id: @transaction_id}
  }

  let(:invalid_attributes) {
    {identifiant:"E123", status:"Nouveau"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LitigesController. Be sure to keep this updated too.
  let(:valid_session) { {user_id:@user.id} }

  let(:valid_admin_session) {
    {user_id:User.first.id}
  }
  
  let(:invalid_session) { {user_id: nil} }
  
  let(:invalid_owner_session) {{user_id: User.third.id}}
  
  describe "GET #index" do
    context "i'm admin", :admin do
      it "assigns all litiges as @litiges" do
        litige = Litige.create! valid_attributes
        get :index, {}
        expect(assigns(:litiges)).to eq(Litige.all)
      end
    end
    
    context "i'm not admin", :owner do
      it "assigns all litiges as @litiges" do
        litige = Litige.create! valid_attributes
        get :index, {}
        expect(assigns(:litiges)).to eq(Litige.tri(@user.id))
      end
    end
  end

  describe "GET #show" do
    context "i'm admin", :admin do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :show, {:id => litige.to_param}
        expect(assigns(:litige)).to eq(litige)
      end
    end
    
    context "i'm owner", :owner do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :show, {:id => litige.to_param}
        expect(assigns(:litige)).to eq(litige)
      end
    end
    
    context "i'm not owner", :not_owner do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :show, {:id => litige.to_param}
        expect(response).to redirect_to root_url
      end      
    end
  end

  describe "GET #new" do
    context "i'm admin", :admin do
      it "assigns a new litige as @litige" do
        get :new, {}
        expect(assigns(:litige)).to be_a_new(Litige)
      end
    end
    
    context "i'm owner", :owner do
      it "redirect to root" do
        get :new, {}
        expect(assigns(:litige)).to be_a_new(Litige)
      end
    end
    
    context "i'm not logged" do
      it "redirect to root" do
        get :new, {}
        expect(response).to redirect_to new_user_session_url
      end
    end
  end

  describe "GET #edit" do
    context "i'm admin", :admin do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :edit, {:id => litige.to_param}
        expect(assigns(:litige)).to eq(litige)
      end
    end
    
    context "i'm owner", :owner do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :edit, {:id => litige.to_param}, valid_session
        expect(assigns(:litige)).to eq(litige)
      end
    end
    
    context "i'm not owner", :not_owner do
      it "assigns the requested litige as @litige" do
        litige = Litige.create! valid_attributes
        get :edit, {:id => litige.to_param}
        expect(assigns(:litige)).to redirect_to root_url
      end
    end
  end

  describe "POST #create" do
    context "i'm admin", :admin do

    end
    
    context "i'm logged", :owner do
      context "with valid params" do
        it "creates a new Litige" do
          expect {
            post :create, {:litige => valid_attributes}
          }.to change(Litige, :count).by(1)
        end
  
        it "assigns a newly created litige as @litige" do
          post :create, {:litige => valid_attributes}
          expect(assigns(:litige)).to be_a(Litige)
          expect(assigns(:litige)).to be_persisted
        end
  
        it "redirects to the created litige" do
          post :create, {:litige => valid_attributes}
          expect(response).to redirect_to(Litige.last)
        end
      end
  
      context "with invalid params" do
        it "assigns a newly created but unsaved litige as @litige" do
          post :create, {:litige => invalid_attributes}
          expect(assigns(:litige)).to be_a_new(Litige)
        end
  
        it "re-renders the 'new' template" do
          post :create, {:litige => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end
    
    context "i'm not logged" do
      it "doesn't post anything" do
        expect {
          post :create, {:litige => valid_attributes}
        }.to change(Litige, :count).by(0)       
      end
      
      it "redirect to root" do
        post :create, {:litige => valid_attributes}
        expect(response).to redirect_to new_user_session_url
      end
    end
  end

  describe "PUT #update" do
    context "i'm admin" do
    end
    
    context "i'm owner", :owner do
      context "with valid params" do
        let(:new_attributes) {
          {identifiant:"ER123", status:"Nouveau", motif:"blahblah"}
        }
  
        it "updates the requested litige" do
          litige = Litige.create! valid_attributes
          put :update, {:id => litige.to_param, :litige => new_attributes}
          litige.reload
        end
  
        it "assigns the requested litige as @litige" do
          litige = Litige.create! valid_attributes
          put :update, {:id => litige.to_param, :litige => valid_attributes}
          expect(assigns(:litige)).to eq(litige)
        end
  
        it "redirects to the litige" do
          litige = Litige.create! valid_attributes
          put :update, {:id => litige.to_param, :litige => valid_attributes}
          expect(response).to redirect_to(litige)
        end
      end
  
      context "with invalid params" do
        it "assigns the litige as @litige" do
          litige = Litige.create! valid_attributes
          put :update, {:id => litige.to_param, :litige => invalid_attributes}
          expect(assigns(:litige)).to eq(litige)
        end
  
        it "re-renders the 'edit' template" do
          litige = Litige.create! valid_attributes
          put :update, {:id => litige.to_param, :litige => invalid_attributes}
          expect(response).to render_template("edit")
        end
      end
    end
    
    context "i'm not owner", :not_owner do
      let(:new_attributes) {
        {zip:"1111111111111111", libelle:"ll", user_id:"1"}
      }
      it "redirect to root" do
        litige = Litige.create! valid_attributes
        put :update, {:id => litige.to_param, :litige => valid_attributes}
        expect(response).to redirect_to root_url
      end
    end
  end

  describe "DELETE #destroy" do
    context "i'm admin", :admin do
      it "destroys the requested litige" do
        litige = Litige.create! valid_attributes
        expect {
          delete :destroy, {:id => litige.to_param}
        }.to change(Litige, :count).by(-1)
      end
  
      it "redirects to the litiges list" do
        litige = Litige.create! valid_attributes
        delete :destroy, {:id => litige.to_param}
        expect(response).to redirect_to(litiges_url)
      end
    end
    
    context "i'm not admin", :owner do
      it "destroys nothing" do
        litige = Litige.create! valid_attributes
        expect {
          delete :destroy, {:id => litige.to_param}
        }.to change(Litige, :count).by(0)
      end
  
      it "redirects to root" do
        litige = Litige.create! valid_attributes
        delete :destroy, {:id => litige.to_param}
        expect(response).to redirect_to root_url
      end
    end
  end
end
